### ISSUE TITLE
Alpha360 - ValueError: calendar not exists for freq day

### ISSUE THREAD

**Issue by ChengYen-Tang** [microsoft/qlib#231]
## 🐛 Bug Description
使用 Alpha158，帶入freq 參數可以正確運作，但是使用 Alpha360，freq 參數沒有用。

## To Reproduce

1. Alpha360

Code:
```
import qlib
from qlib.contrib.data.handler import Alpha360
from qlib.data import D

qlib.init(provider_uri='~/.qlib/qlib_data/my_data/')
instruments = D.instruments(market='all')

data_handler_config = {
    'start_time': '2019-01-01',
    'end_time': '2021-01-15',
    'fit_start_time': '2019-01-01',
    'fit_end_time': '2020-06-30',
    'instruments': instruments,
    'freq': '30m'
}

h = Alpha360(**data_handler_config)
print(h.get_cols())
```
Result:
```
TypeError                                 Traceback (most recent call last)
~/.local/lib/python3.8/site-packages/pyqlib-0.6.1.99-py3.8-linux-x86_64.egg/qlib/data/data.py in features(self, instruments, fields, start_time, end_time, freq, disk_cache)
    966         try:
--> 967             return DatasetD.dataset(instruments, fields, start_time, end_time, freq, disk_cache)
    968         except TypeError:

TypeError: dataset() takes from 3 to 6 positional arguments but 7 were given

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-2-baee302976db> in <module>
      8 }
      9 
---> 10 h = Alpha360(**data_handler_config)
     11 
     12 print(h.get_cols())

~/.local/lib/python3.8/site-packages/pyqlib-0.6.1.99-py3.8-linux-x86_64.egg/qlib/contrib/data/handler.py in __init__(self, instruments, start_time, end_time, freq, infer_processors, learn_processors, fit_start_time, fit_end_time, filter_pipe, **kwargs)
     72         }
     73 
---> 74         super().__init__(
     75             instruments=instruments,
     76             start_time=start_time,

~/.local/lib/python3.8/site-packages/pyqlib-0.6.1.99-py3.8-linux-x86_64.egg/qlib/data/dataset/handler.py in __init__(self, instruments, start_time, end_time, freq, data_loader, infer_processors, learn_processors, process_type, drop_raw, **kwargs)
    329         self.process_type = process_type
    330         self.drop_raw = drop_raw
--> 331         super().__init__(instruments, start_time, end_time, freq, data_loader, **kwargs)
    332 
    333     def get_all_processors(self):

~/.local/lib/python3.8/site-packages/pyqlib-0.6.1.99-py3.8-linux-x86_64.egg/qlib/data/dataset/handler.py in __init__(self, instruments, start_time, end_time, freq, data_loader, init_data, fetch_orig)
    100         if init_data:
    101             with TimeInspector.logt("Init data"):
--> 102                 self.init()
    103         super().__init__()
    104 

~/.local/lib/python3.8/site-packages/pyqlib-0.6.1.99-py3.8-linux-x86_64.egg/qlib/data/dataset/handler.py in init(self, init_type, enable_cache)
    413         """
    414         # init raw data
--> 415         super().init(enable_cache=enable_cache)
    416 
    417         with TimeInspector.logt("fit & process data"):

~/.local/lib/python3.8/site-packages/pyqlib-0.6.1.99-py3.8-linux-x86_64.egg/qlib/data/dataset/handler.py in init(self, enable_cache)
    124         # _data may be with multiple column index level. The outer level indicates the feature set name
    125         with TimeInspector.logt("Loading data"):
--> 126             self._data = self.data_loader.load(self.instruments, self.start_time, self.end_time, self.freq)
    127         # TODO: cache
    128 

~/.local/lib/python3.8/site-packages/pyqlib-0.6.1.99-py3.8-linux-x86_64.egg/qlib/data/dataset/loader.py in load(self, instruments, start_time, end_time, freq)
    122         if self.is_group:
    123             df = pd.concat(
--> 124                 {
    125                     grp: self.load_group_df(instruments, exprs, names, start_time, end_time, freq)
    126                     for grp, (exprs, names) in self.fields.items()

~/.local/lib/python3.8/site-packages/pyqlib-0.6.1.99-py3.8-linux-x86_64.egg/qlib/data/dataset/loader.py in <dictcomp>(.0)
    123             df = pd.concat(
    124                 {
--> 125                     grp: self.load_group_df(instruments, exprs, names, start_time, end_time, freq)
    126                     for grp, (exprs, names) in self.fields.items()
    127                 },

~/.local/lib/python3.8/site-packages/pyqlib-0.6.1.99-py3.8-linux-x86_64.egg/qlib/data/dataset/loader.py in load_group_df(self, instruments, exprs, names, start_time, end_time, freq)
    170             warnings.warn("`filter_pipe` is not None, but it will not be used with `instruments` as list")
    171 
--> 172         df = D.features(instruments, exprs, start_time, end_time, freq)
    173         df.columns = names
    174         if self.swap_level:

~/.local/lib/python3.8/site-packages/pyqlib-0.6.1.99-py3.8-linux-x86_64.egg/qlib/data/data.py in features(self, instruments, fields, start_time, end_time, freq, disk_cache)
    967             return DatasetD.dataset(instruments, fields, start_time, end_time, freq, disk_cache)
    968         except TypeError:
--> 969             return DatasetD.dataset(instruments, fields, start_time, end_time, freq)
    970 
    971 

~/.local/lib/python3.8/site-packages/pyqlib-0.6.1.99-py3.8-linux-x86_64.egg/qlib/data/data.py in dataset(self, instruments, fields, start_time, end_time, freq)
    690 
    691     def dataset(self, instruments, fields, start_time=None, end_time=None, freq="day"):
--> 692         instruments_d = self.get_instruments_d(instruments, freq)
    693         column_names = self.get_column_names(fields)
    694         cal = Cal.calendar(start_time, end_time, freq)

~/.local/lib/python3.8/site-packages/pyqlib-0.6.1.99-py3.8-linux-x86_64.egg/qlib/data/data.py in get_instruments_d(instruments, freq)
    368             if "market" in instruments:
    369                 # dict of stockpool config
--> 370                 instruments_d = Inst.list_instruments(instruments=instruments, freq=freq, as_list=False)
    371             else:
    372                 # dict of instruments and timestamp

~/.local/lib/python3.8/site-packages/pyqlib-0.6.1.99-py3.8-linux-x86_64.egg/qlib/data/data.py in list_instruments(self, instruments, start_time, end_time, freq, as_list)
    595         # strip
    596         # use calendar boundary
--> 597         cal = Cal.calendar(freq=freq)
    598         start_time = pd.Timestamp(start_time or cal[0])
    599         end_time = pd.Timestamp(end_time or cal[-1])

~/.local/lib/python3.8/site-packages/pyqlib-0.6.1.99-py3.8-linux-x86_64.egg/qlib/data/data.py in calendar(self, start_time, end_time, freq, future)
    532 
    533     def calendar(self, start_time=None, end_time=None, freq="day", future=False):
--> 534         _calendar, _calendar_index = self._get_calendar(freq, future)
    535         if start_time == "None":
    536             start_time = None

~/.local/lib/python3.8/site-packages/pyqlib-0.6.1.99-py3.8-linux-x86_64.egg/qlib/data/data.py in _get_calendar(self, freq, future)
    118             _calendar, _calendar_index = H["c"][flag]
    119         else:
--> 120             _calendar = np.array(self.load_calendar(freq, future))
    121             _calendar_index = {x: i for i, x in enumerate(_calendar)}  # for fast search
    122             H["c"][flag] = _calendar, _calendar_index

~/.local/lib/python3.8/site-packages/pyqlib-0.6.1.99-py3.8-linux-x86_64.egg/qlib/data/data.py in load_calendar(self, freq, future)
    527             fname = self._uri_cal.format(freq)
    528         if not os.path.exists(fname):
--> 529             raise ValueError("calendar not exists for freq " + freq)
    530         with open(fname) as f:
    531             return [pd.Timestamp(x.strip()) for x in f]

ValueError: calendar not exists for freq day
```

## Expected Behavior

1. Alpha158

Code:
```
import qlib
from qlib.contrib.data.handler import Alpha158
from qlib.data import D

qlib.init(provider_uri='~/.qlib/qlib_data/my_data/')
instruments = D.instruments(market='all')

data_handler_config = {
    'start_time': '2019-01-01',
    'end_time': '2021-01-15',
    'fit_start_time': '2019-01-01',
    'fit_end_time': '2020-06-30',
    'instruments': instruments,
    'freq': '30m'
}

h = Alpha158(**data_handler_config)
print(h.get_cols())
```
Result:
```
['KMID', 'KLEN', 'KMID2', 'KUP', 'KUP2', 'KLOW', 'KLOW2', 'KSFT', 'KSFT2', 'OPEN0', 'HIGH0', 'LOW0', 'VWAP0', 'ROC5', 'ROC10', 'ROC20', 'ROC30', 'ROC60', 'MA5', 'MA10', 'MA20', 'MA30', 'MA60', 'STD5', 'STD10', 'STD20', 'STD30', 'STD60', 'BETA5', 'BETA10', 'BETA20', 'BETA30', 'BETA60', 'RSQR5', 'RSQR10', 'RSQR20', 'RSQR30', 'RSQR60', 'RESI5', 'RESI10', 'RESI20', 'RESI30', 'RESI60', 'MAX5', 'MAX10', 'MAX20', 'MAX30', 'MAX60', 'MIN5', 'MIN10', 'MIN20', 'MIN30', 'MIN60', 'QTLU5', 'QTLU10', 'QTLU20', 'QTLU30', 'QTLU60', 'QTLD5', 'QTLD10', 'QTLD20', 'QTLD30', 'QTLD60', 'RANK5', 'RANK10', 'RANK20', 'RANK30', 'RANK60', 'RSV5', 'RSV10', 'RSV20', 'RSV30', 'RSV60', 'IMAX5', 'IMAX10', 'IMAX20', 'IMAX30', 'IMAX60', 'IMIN5', 'IMIN10', 'IMIN20', 'IMIN30', 'IMIN60', 'IMXD5', 'IMXD10', 'IMXD20', 'IMXD30', 'IMXD60', 'CORR5', 'CORR10', 'CORR20', 'CORR30', 'CORR60', 'CORD5', 'CORD10', 'CORD20', 'CORD30', 'CORD60', 'CNTP5', 'CNTP10', 'CNTP20', 'CNTP30', 'CNTP60', 'CNTN5', 'CNTN10', 'CNTN20', 'CNTN30', 'CNTN60', 'CNTD5', 'CNTD10', 'CNTD20', 'CNTD30', 'CNTD60', 'SUMP5', 'SUMP10', 'SUMP20', 'SUMP30', 'SUMP60', 'SUMN5', 'SUMN10', 'SUMN20', 'SUMN30', 'SUMN60', 'SUMD5', 'SUMD10', 'SUMD20', 'SUMD30', 'SUMD60', 'VMA5', 'VMA10', 'VMA20', 'VMA30', 'VMA60', 'VSTD5', 'VSTD10', 'VSTD20', 'VSTD30', 'VSTD60', 'WVMA5', 'WVMA10', 'WVMA20', 'WVMA30', 'WVMA60', 'VSUMP5', 'VSUMP10', 'VSUMP20', 'VSUMP30', 'VSUMP60', 'VSUMN5', 'VSUMN10', 'VSUMN20', 'VSUMN30', 'VSUMN60', 'VSUMD5', 'VSUMD10', 'VSUMD20', 'VSUMD30', 'VSUMD60', 'LABEL0']
```

## Environment

**Note**: User could run `cd scripts && python collect_info.py all` under project directory to get system information
and paste them here directly.

 - Qlib version:
 - Python version: 3.8.7
 - OS (`Windows`, `Linux`, `MacOS`): Linux
 - Commit number (optional, please provide it if you are using the dev version): https://github.com/microsoft/qlib/commit/c0e7cbc9830c1149c7ef0823553f3b15a0936df1

**Comment by you-n-g** [comment]
Currently, data of `'freq': '30m'` are not privided in the opensource version.
Thanks.

**Comment by ChengYen-Tang** [comment]
你好，我有自己準備 30m 的資料集
但是從錯誤訊息來看，參數沒有正確傳遞到後面的 method。
`calendar not exists for freq day`

謝謝

**Comment by bxdd** [comment]
Thanks for your feedback, the bug is being resolved in #236.

**Comment by SandeepKS1988** [comment]
Hi Guys,

I still see this error while using the code form the documentation.

`from qlib.data import D`
`instruments = D.instruments(market='csi300')`
`D.list_instruments(instruments=instruments, start_time='2010-01-01', end_time='2017-12-31', as_list=True)[:6]`

`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-8-81dee0087bb6>](https://localhost:8080/#) in <cell line: 3>()
      1 from qlib.data import D
      2 instruments = D.instruments(market='csi300')
----> 3 D.list_instruments(instruments=instruments, start_time='2010-01-01', end_time='2017-12-31', as_list=True)[:6]

5 frames
[/usr/local/lib/python3.10/dist-packages/qlib/data/storage/file_storage.py](https://localhost:8080/#) in uri(self)
     60     def uri(self) -> Path:
     61         if self.freq not in self.support_freq:
---> 62             raise ValueError(f"{self.storage_name}: {self.provider_uri} does not contain data for {self.freq}")
     63         return self.dpm.get_data_uri(self.freq).joinpath(f"{self.storage_name}s", self.file_name)
     64 

ValueError: instrument: {'__DEFAULT_FREQ': '/root/.qlib/qlib_data/my_data'} does not contain data for day`

Regards,
Sandeep KS
