### ISSUE TITLE
ModuleNotFoundError: No module named 'qlib.contrib.strategy.model_strategy' on workflow notebook example

### ISSUE THREAD

**Issue by kurucan** [microsoft/qlib#714]
I am running the workflow example notebook, I get the error below: I think this is looking to old backtest?

ModuleNotFoundError: No module named 'qlib.contrib.strategy.model_strategy'

https://github.com/microsoft/qlib/tree/main/examples/workflow_by_code.ipynb

**Comment by Wangwuyi123** [comment]
@kurucan 
Please tell me which line of code caused the error so that I can reproduce it in my environment.

**Comment by zhupr** [comment]
@kurucan Hi,
This issue has been resolved #697, please update to the latest code at: `pip install git+https://github.com/microsoft/qlib.git -U`

**Comment by Queituron** [comment]
@kurucan Hi,

I am following this bug. I'm still having the same issues after the suggested update.

I ran the tests in workflow_by_code.py and workflow_by_code.ipynb.

**Comment by zhupr** [comment]
> @kurucan Hi,
> 
> I am following this bug. I'm still having the same issues after the suggested update.
> 
> I ran the tests in workflow_by_code.py and workflow_by_code.ipynb.

You also need to `clone` or `pull` the latest code locally
